# Generated by Django 4.1 on 2024-06-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_mgroup_name_alter_muser_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mgroup",
            name="created_at",
        ),
    ]
