# Generated by Django 5.0.6 on 2024-06-07 10:55

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_remove_mgroup_created_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="muser",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="muser",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="muser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="muser",
            name="manito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="muser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="muser",
            name="username",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="muser",
            constraint=models.UniqueConstraint(
                fields=("username", "group"), name="unique_username_per_group"
            ),
        ),
    ]
