# Generated by Django 5.0.6 on 2024-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_muser_managers_alter_muser_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="muser",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
