# Generated by Django 5.0.6 on 2024-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="mgroup",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
