# Generated by Django 5.0.6 on 2024-06-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_mgroup_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="muser",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
