# Generated by Django 5.0.6 on 2024-06-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_muser_is_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="muser",
            name="password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
