# Generated by Django 5.0.6 on 2024-06-18 11:24

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0007_mgroup_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "muser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_manager", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Manager",
                "verbose_name_plural": "Managers",
                "permissions": [("manage_group", "Can manage group")],
            },
            bases=("users.muser",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
