# Generated by Django 4.1 on 2024-05-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_manito", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="muser",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="muser",
            unique_together={("username", "group")},
        ),
    ]
