# Generated by Django 4.1 on 2024-05-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_manito", "0002_alter_muser_options_alter_muser_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muser",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
