# Generated by Django 4.1 on 2024-05-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_manito", "0004_alter_muser_manito"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="muser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterUniqueTogether(
            name="muser",
            unique_together=set(),
        ),
    ]
