# Generated by Django 4.1 on 2024-05-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_manito", "0005_alter_muser_options_alter_muser_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="muser",
            name="nickname",
        ),
    ]
