# Generated by Django 4.1 on 2024-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_manito", "0008_alter_muser_options_alter_muser_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="muser",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="muser",
            constraint=models.UniqueConstraint(
                fields=("username", "group"), name="unique_username_group"
            ),
        ),
    ]
