# Generated by Django 4.1 on 2024-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_manito", "0009_alter_muser_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="muser",
            name="unique_username_group",
        ),
        migrations.AlterField(
            model_name="muser",
            name="username",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name="muser",
            unique_together={("username", "group")},
        ),
    ]
